name: CosmicSMP-API
version: 1.0.1
main: withicality.csmp.api.MainClass
api-version: '1.19'
authors: [ Withicality ]
description: Plugin for CosmicSMP
website: withicality.tk
depend:
  - WithicalUtilities
  - ProtocolLib
softdepend:
  - JukeboxExtended