name: CosmicSMP-Global
version: 1.0.1
main: withicality.csmp.global.CosmicGlobal
api-version: 1.19
authors: [ Withicality ]
description: Plugin for CosmicSMP
website: withicality.tk
depend:
  - CosmicSMP-API